name = "futures-radar-worker"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = true

# Cron: รันทุก 1 นาที
[triggers]
crons = ["* * * * *"]

# KV namespace for signal data storage and cron results
[[kv_namespaces]]
binding = "SIGNAL_KV"
id = "daa5f58e90f04dd4b01e528eb1a7cbab"
